### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by eav-eav-eav**
Seen that this file is out of date and has some mistakes, I'm gonna have a try.

Btw, I'm a bit confused about the "Directional Scrolling", which I didn't figure out the actual usage, so I left it. 🤔

### CODE REVIEW

**Comment by eav-eav-eav** [comment]
Add TODO: "从物品栏中抽取工具" to "允许从物品栏中抽取工具"

**Comment by Siphalor** [comment]
Hey, thanks for your work :)

> Btw, I'm a bit confused about the "Directional Scrolling", which I didn't figure out the actual usage, so I left it. 🤔

Directional Scrolling means that if you scroll up on a stack it will send the item to the container literally above the slot and vice-versa for scrolling downwards.
Inventory Tweaks has a default scrolling variant where if you scroll up on an item, it will try to find a matching stack in the opposite inventory and move that to wherever you scrolled.
If you disable the directional scrolling option the Inventory Tweaks style scrolling is performed.

By the way: by appending `.description` to config translations you can translate the text that's shown when you hover it.
For the default locale this has to be done in the Java code so you can not see this in the `en_us.json` but only in [the config class](https://github.com/Siphalor/mouse-wheelie/blob/1.16/src/main/java/de/siphalor/mousewheelie/MWConfig.java).

**Comment by eav-eav-eav** [comment]
> Hey, thanks for your work :)
> 
> > Btw, I'm a bit confused about the "Directional Scrolling", which I didn't figure out the actual usage, so I left it. 🤔
> 
> Directional Scrolling means that if you scroll up on a stack it will send the item to the container literally above the slot and vice-versa for scrolling downwards.
> ...

Oh I got it! 😄
How about the description in the [Line 32](https://github.com/Siphalor/mouse-wheelie/blob/1.16/src/main/java/de/siphalor/mousewheelie/MWConfig.java#L32)? Is there a key to access it?
Also, I used `\n` to add line breaks but it failed, so how to instead? 😕

**Comment by Siphalor** [comment]
> How about the description in the [Line 32](https://github.com/Siphalor/mouse-wheelie/blob/1.16/src/main/java/de/siphalor/mousewheelie/MWConfig.java#L32)? Is there a key to access it?

Not yet, but in the next release of the config library you'll be able to change that with the usual `.description` syntax. So just use that and when I update the config library the changes will get applied :)

> Also, I used `\n` to add line breaks but it failed, so how to instead? 😕

Wasn't sure about that myself actually. So I tried looking it up in the Minecraft wiki and it didn't tell anything about it.  
Then I decided to look at the German Minecraft wiki which is way more concise about the data formats and that tells that you just break the line at that position.  
Yeah, it seems to be that easy 🤦‍♂️

Also, since you marked this pr as ready, can I merge this when you fixed the line breaks and added the description?

**Comment by eav-eav-eav** [comment]
Yep. :D

**Pull request merged**
