### PR TITLE
Slightly improve creative scrolling settings, fix fixConfig

### PR DESCRIPTION
**Pull request by Fourmisain**
- Add setting for creative tab scrolling (defaults to on)
 - Change 'scroll creative menu' to 'scroll creative menu items', which has the reversed meaning
This is a bit more intuitive, since it's a now feature you turn on or off, rather than a switch which returns to vanilla behavior when it's `true`
 - fix `fixConfig` so that it deletes obsolete settings
If they're not deleted, the new settings will be overwritten every reload

I also adjusted the translations a bit, no idea on the Estonian.
A related question to this:
Is it possible to add translations for the `@AConfigEntry` `comment`s (the mouseover text boxes) as well?

### CODE REVIEW

**Comment by Fourmisain** [comment]
This should be enough to close https://github.com/Siphalor/mouse-wheelie/issues/92, I'm not entirely sure what I meant by the scrolling entering a 'locked state' anymore, but if it's an issue, it should then be a separate one.

**Comment by Siphalor** [comment]
Looks pretty good :+1:

> A related question to this:
> Is it possible to add translations for the @AConfigEntry comments (the mouseover text boxes) as well?

I originally didn't want to do that because the description needs to be untranslated for the config file. But I think I'm gonna add a check if a translation exists and otherwise just default to the comment.

The biggest problem with Tweed is still that it is very poorly documented, especially the annotated variation.

**Comment by Siphalor** [comment]
Also you earned the right to call yourself a contributor :)
I'm gonna add you to the `fabric.mod.json` soon 😃 

Tweeds translatable descriptions will arrive in the next beta btw

**Comment by Fourmisain** [comment]
Haha, I only fixed a bug or two, so no need!

**Pull request merged**
